# Generated by Django 5.1.7 on 2025-03-27 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writeups.subcategory'),
        ),
    ]
