# Generated by Django 5.1.7 on 2025-04-10 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('writeups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteupRootPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Writeups Container',
            },
            bases=('wagtailcore.page',),
        ),
    ]
