# Generated by Django 5.1.7 on 2025-03-27 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_image'),
        ('writeups', '0002_alter_writeup_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='writeup',
            name='category',
        ),
        migrations.AddField(
            model_name='writeup',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='writeup',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='writeup',
            name='source',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writeup',
            name='difficulty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='writeups.difficulty'),
        ),
    ]
