# Generated by Django 5.1.7 on 2025-03-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0003_difficulty_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='source',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
