# Generated by Django 5.1.7 on 2025-03-27 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0004_alter_writeup_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writeup',
            old_name='source',
            new_name='notion_link',
        ),
    ]
