# Generated by Django 5.1.7 on 2025-04-18 20:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0004_rootpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('code', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('c', 'C'), ('csharp', 'C#'), ('cpp', 'C++'), ('diff', 'diff'), ('html', 'HTML'), ('java', 'Java'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('text', 'Plain Text'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'label': 'Code'})}, help_text='Note to writers: Keep in mind that any reader of this writeup is most likely not coming from a CTF, but from a social media platform where a link to our website was shared. The reader does not have access to the source, so you must show as much information as possible using images and code. Make the reader feel like hes there solving the challenge with you and try to make sources that the reader can try to solve on his own'),
        ),
    ]
