# Generated by Django 5.1.7 on 2025-04-24 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0005_alter_writeup_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeup',
            options={'ordering': ['-date'], 'verbose_name': 'Writeup'},
        ),
        migrations.AddField(
            model_name='writeup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the article is published', verbose_name='Post date'),
        ),
    ]
