# Generated by Django 5.1.7 on 2025-03-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0005_rename_source_writeup_notion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/'),
        ),
    ]
