# Generated by Django 5.1.7 on 2025-03-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0006_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
