# Generated by Django 5.1.7 on 2025-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_image'),
        ('writeups', '0007_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='author',
        ),
        migrations.AddField(
            model_name='writeup',
            name='author',
            field=models.ManyToManyField(to='members.member'),
        ),
    ]
