# Generated by Django 5.1.7 on 2025-03-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='portraits/placeholder.png', upload_to='portraits/'),
        ),
    ]
