# Generated by Django 5.1.7 on 2025-04-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='member',
            name='github',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
