# Generated by Django 5.1.7 on 2025-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='member',
            name='github',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
