# Generated by Django 5.1.7 on 2025-04-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_major_university_member_major_member_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
