# Generated by Django 5.1.7 on 2025-04-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_major_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
