# Generated by Django 5.1.7 on 2025-04-24 19:26

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_remove_member_description_remove_member_email'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogRootPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Blogs Container',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the article is published', verbose_name='Post date')),
                ('blog_type', models.CharField(max_length=50)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('code', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bash', 'Bash/Shell'), ('css', 'CSS'), ('c', 'C'), ('csharp', 'C#'), ('cpp', 'C++'), ('diff', 'diff'), ('html', 'HTML'), ('java', 'Java'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('text', 'Plain Text'), ('yaml', 'YAML')], 'help_text': 'Coding language', 'identifier': 'language', 'label': 'Language'}), 2: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}), 3: ('wagtail.blocks.StructBlock', [[('language', 1), ('code', 2)]], {'label': 'Code'})})),
                ('author', models.ManyToManyField(help_text='Ctrl + Click to select more than one author', related_name='blogs', to='members.member')),
            ],
            options={
                'verbose_name': 'Blog',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
