# Generated by Django 5.1.7 on 2025-04-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogchildpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
